batch_size: 20
datasets:
  git: https://github.com/user-mlgit/demo
labels:
  git: https://github.com/user-mlgit/demo-labels
store:
  s3h:
    mlgit-datasets:
      aws-credentials:
        profile: default
      region: us-east-1
